display:
  background:
    path: /home/theo/.config/thermalright-lcd-control/themes/backgrounds/gIODGWDBuG5AWlUExJ.mp4
    type: video
  date:
    color: '#FFFFFFFF'
    enabled: false
    font_size: 19
    position:
      x: 15
      y: 3
    text: ''
  foreground:
    alpha: 1.0
    enabled: true
    path: /home/theo/.config/thermalright-lcd-control/themes/foregrounds/{resolution}/000e.png
    position:
      x: 0
      y: 0
  metrics:
    configs:
    - color: '#FFFFFFFF'
      enabled: true
      font_size: 19
      format_string: '{label}{value}{unit}'
      label: CPU
      name: cpu_temperature
      position:
        x: 93
        y: 7
      unit: °
    - color: '#FFFFFFFF'
      enabled: true
      font_size: 19
      format_string: '{label}{value}{unit}'
      label: GPU
      name: gpu_temperature
      position:
        x: 102
        y: 288
      unit: °
    enabled: true
  rotation: 0
  time:
    color: '#FFFFFFFF'
    enabled: false
    font_size: 19
    position:
      x: 155
      y: 141
    text: ''
