# SPDX-License-Identifier: Apache-2.0
# Copyright Â© 2025 Rejeb Ben Rejeb

paths:
  themes_dir: "/home/theo/.config/thermalright-lcd-control/themes/presets"
  backgrounds_dir: "/home/theo/.config/thermalright-lcd-control/themes/backgrounds"
  foregrounds_dir: "/home/theo/.config/thermalright-lcd-control/themes/foregrounds"
  service_config: "/home/theo/.config/thermalright-lcd-control/config"
window:
  default_width: 1920
  default_height: 1080
  min_width: 800
  min_height: 600

supported_formats:
  images: [ '.jpg', '.jpeg', '.png', '.bmp', '.tiff', '.webp' ]
  videos: [ '.mp4', '.avi', '.mkv', '.mov', '.webm', '.flv', '.wmv', '.m4v' ]
  gifs: [ '.gif' ]
